#!/bin/bash
set -e

KUBECONFDIR="${HOME}/kubeconf"
KUBECONFIGNAME="kubeconfig"
KUBECONFIGURL=$1

WGET=`which wget`
if (echo ${WGET} | grep -E "not found") || (echo ${WGET} | grep -E "no ") ; then
  echo "There is no wget installed or added into PATH"
  exit 1
fi

echo "try to get kubeconfig ${KUBECONFIGURL}"

current=`date "+%Y-%m-%d %H:%M:%S"`  
date_str=`echo ${current} | awk -F " " '{print $1}'`
time_str=`echo ${current} | awk -F " " '{print $2}'`
config_name="kubeconfig-${date_str}-${time_str}"
echo "the new kubeconfig file is ${config_name}"

cd ${KUBECONFDIR}
${WGET} --no-check-certificate ${KUBECONFIGURL} -O ${config_name}

if [ $? -ne 0 ];then
  echo "the new kubeconfig file is not downloaded, please check the reason. still keep existing kubeconfig file"
  exit 1
fi
echo "succeed to get ${config_name}"

rm -fr ${KUBECONFIGNAME}
ln -s ${config_name} ${KUBECONFIGNAME}
echo "the new kubeconfig file ${config_name} take effective"

