#!/bin/bash
set -e

AZUREAUTHDIR="/root/azureauth"
AZUREAUTHFILE="azure_auth.json"
AZUREAUTHURL=$1

WGET=`which wget`
if (echo ${WGET} | grep -E "not found") || (echo ${WGET} | grep -E "no ") ; then
    echo "There is no wget installed or added into PATH"
    exit 1
fi

echo "try to get azure auth file ${AZUREAUTHURL}"

current=`date "+%Y-%m-%d %H:%M:%S"`
date_str=`echo ${current} | awk -F " " '{print $1}'`
time_str=`echo ${current} | awk -F " " '{print $2}'`
config_name="terraform.azure.auto.tfvars-${date_str}-${time_str}.json"
echo "the new azure auth file file is ${config_name}"

cd ${AZUREAUTHDIR}
${WGET} --no-check-certificate ${AZUREAUTHURL} -O ${config_name}

if [ $? -ne 0 ];then
    echo "the new azure auth file file is not downloaded, please check the reason. still keep existing azure auth file file"
    exit 1
fi
echo "succeed to get ${config_name}"

rm -fr ${AZUREAUTHFILE}
ln -s ${config_name} ${AZUREAUTHFILE}
echo "the new azure auth file file ${config_name} take effective"

