#!/bin/bash
set +x
#generae report

WORKBUILDDIR=$1
WORKSPACE=$2

cd ${WORKBUILDDIR}
resultfile=`ls -rt -1 junit_e2e_* 2>&1 || true`
echo $resultfile
if (echo $resultfile | grep -E "no matches found") || (echo $resultfile | grep -E "No such file or directory") ; then
  echo "there is no result file generated"
  exit 1
fi
current_time=`date "+%Y-%m-%d-%H-%M-%S"`
newresultfile="junit_e2e_"${current_time}".xml"
rm -fr handleresult.py && eval cp -fr ${WORKSPACE}"/private/pipeline/handleresult.py" .
python3 handleresult.py -a replace -i ${resultfile} -o ${newresultfile} && rm -fr ${resultfile}
resultsummary=`python3 handleresult.py -a get -i ${newresultfile} 2>&1 || true`
if (echo $resultsummary | grep -q -E "FAIL") ; then
  finalresult="FAIL"
else
  finalresult="SUCCESS"
fi
echo -e "\n\n\n"
echo -e ${resultsummary}
if [ "${finalresult}" == "SUCCESS" ] ; then
  echo "the build is SUCCESS"
  exit 0
else
  echo "the build is FAIL"
  exit 1
fi
set -x
