#!/bin/bash

function run {
  repo_owner="$1"
  case_scenario="$2"
  case_importance="$3"
  case_filter="$4"

  make clean
  if [ "${repo_owner}" == "openshift" ]; then
    echo "make all"
    make all
  else
    echo "make build"
    make build
  fi

  if [ "${case_importance}" == "all" ]; then
    case_importance=""
  fi
  ./bin/extended-platform-tests run all --dry-run | \
    grep -E "${case_scenario}" | grep -i -E "${case_importance}" > ./case_selected

  handle_filters "${case_filter}"
  echo "------------------the case selected------------------"
  cat ./case_selected
  echo "-----------------------------------------------------"

  ./bin/extended-platform-tests run --max-parallel-tests 6 --timeout 35m --junit-dir=./ -f ./case_selected
  rm -fr ./case_selected
}

function handle_filters {
  filter_tmp="$1"
  if [ "${filter_tmp}" == "null" ]; then
    echo "there is no filter"
    return
  fi
  echo "try to handler filters..."
  filter_tmp=${filter_tmp:4}
  filters=(${filter_tmp//;/ })

  filters_and=()
  filters_or=()
  for filter in "${filters[@]}"
  do
    echo "${filter}"
    valid_filter "${filter}"
    filter_logical="$(echo $filter | grep -Eo '[&]?$')"

    if [ "W${filter_logical}W" == "W&W" ]; then
      filters_and+=(${filter})
    else
      filters_or+=(${filter})
    fi
  done

  for filter in ${filters_and[*]}
  do
    echo "handle filter_and ${filter}"
    handle_and_filter "${filter}"
  done

  rm -fr ./case_selected_or
  for filter in ${filters_or[*]}
  do
    echo "handle filter_or ${filter}"
    handle_or_filter "${filter}"
  done
  [ -e ./case_selected_or ] && sort -u ./case_selected_or > ./case_selected && rm -fr ./case_selected_or
}

function valid_filter {
  filter="$1"
  if ! echo ${filter} | grep -E '^[~]?[a-zA-Z0-9]{1,}[&]?$'; then
    echo "the filter "${filter}" is not correct format. it should be ^[~]?[a-zA-Z0-9]{1,}[&]?$"
    exit 1
  fi
  action="$(echo $filter | grep -Eo '^[~]?')"
  value="$(echo $filter | grep -Eo '[a-zA-Z0-9]{1,}')"
  logical="$(echo $filter | grep -Eo '[&]?$')"
  echo $action"--"$value"--"$logical
}

function handle_and_filter {
  action="$(echo $1 | grep -Eo '^[~]?')"
  value="$(echo $1 | grep -Eo '[a-zA-Z0-9]{1,}')"

  if [ "W${action}W" == "WW" ]; then
    cat ./case_selected | grep -i -E "${value}" > ./case_selected_and
  else
    cat ./case_selected | grep -i -v -E "${value}" > ./case_selected_and
  fi
  [ -e ./case_selected_and ] && cp -fr ./case_selected_and ./case_selected && rm -fr ./case_selected_and
}
function handle_or_filter {
  action="$(echo $1 | grep -Eo '^[~]?')"
  value="$(echo $1 | grep -Eo '[a-zA-Z0-9]{1,}')"

  if [ "W${action}W" == "WW" ]; then
    cat ./case_selected | grep -i -E "${value}" >> ./case_selected_or
  else
    cat ./case_selected | grep -i -v -E "${value}" >> ./case_selected_or
  fi
}
run "$1" "$2" "$3" "$4"
