#!/bin/bash

make clean
if [ "$3" == "openshift" ]; then
  make all
else
  make build
fi
./bin/extended-platform-tests run all --dry-run | \
  grep -E "$1" | grep -i -E "$2" | \
  ./bin/extended-platform-tests run --junit-dir=./ -f -