FROM registry.ci.openshift.org/ocp/4.10:tools
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    PACKAGES="openssh-clients httpd-tools nodejs yarn" && \
    yum install --setopt=tsflags=nodocs -y $PACKAGES && yum clean all && rm -rf /var/cache/yum/*
COPY frontend frontend
